// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kftgoeeqjbxflktgkgdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmdGdvZWVxamJ4ZmxrdGdrZ2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjY3ODYsImV4cCI6MjA3Mzk0Mjc4Nn0.PyFtzBO4WQzLXv_RjpF_gq5fUpzpFDFgrepNQodPUHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});